#!/bin/bash

# Must be run as root
if [[ $EUID -ne 0 ]]; then
	echo "This script must be run as root"
	exit 1
fi

# Global Variables
VERBOSE=1

# Internal functions
validate_ip() {
    [ $VERBOSE -eq 1 ] && echo "Validating ip..."

	local ip=$1
	if [[ $ip =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
		IFS='.' read -r -a octets <<< "$ip"
		for octet in "${octets[@]}"; do
			if ! [[ "$octet" -ge 0 && "$octet" -le 255 ]]; then
				return 1  # Invalid IP range
			fi
		done
		return 0  # Valid IP address
	else
		return 1  # Invalid IP format
	fi
}

netmgr_exec_node(){
	[ $VERBOSE -eq 1 ] && echo "Executing commands to node with ip=$2..."
	local path=$1
	local ip=$2
	local name=$3
	local library=$4
	local method=$5
	local username=$6
	local password=$7
	local action=$8
	local fullpath=""
	local libpath=""

	if [ -z "$ip" ]; then
		echo "Error: ip address is required"
		return 1
	elif ! validate_ip "$ip"; then
		echo "Error: ip address $ip is invalid"
		return 1
	elif [ "$method" != "none" ]; then
		[ $VERBOSE -eq 1 ] && echo "Loading node library..."
		libpath="$NETMGR_LIB_PATH/$library"

		if [ ! -f "$libpath" ]; then
			echo "Error: Library $libpath does not exist"
			return 1
		fi	

		(
			source "$libpath"

			[ $VERBOSE -eq 1 ] && echo "Gaining access to network appliance..."
			lib_execute_ssh "$method" "$ip" "$username" "$password" "$action"
		)
		[ $? -ne 0 ] && return $?
		return 0
	fi

	return 0
}

# Commands
func_show_help(){
	echo "Usage: $0 [-s] [-c config] [-f file] [-x commands]" 	
}

main(){
	local config="./etc/wazuh_netmgr.conf"
	local action=""
	local file=""
	local total=0
	local success=0

	# Set opt index
	OPTIND=1

	while getopts "h?sc:x:f:" opt; do
		case "$opt" in
		h|\?)	func_show_help && exit 0	;;
		s)	VERBOSE=0			;;
		c)	config=$OPTARG			;;
		f)	file=$OPTARG			;;
		x)	action=$OPTARG			;;
		esac
	done
	shift $((OPTIND-1))

	# Loads config
	if [ -f "$config" ]; then
		source "$config"
	else
		echo "Error: Configuration file $config not found or is not a regular file."
		exit 1
	fi

	if [ ! -f "$file" ]; then
		echo "Error: File $file not found"
		exit 1
	fi

	while IFS=';' read -r path ip name library method username password; do
		if [[ -z "$path" || "$path" == "#"* ]]; then
			continue
		fi
		netmgr_exec_node "$path" "$ip" "$name" "$library" "$method" "$username" "$password" "$action"
		[ $? -eq 0 ] && ((success++))
		((total++))

	done < "$file"

	echo "Command has been executed on $success/$total Nodes from $file."
}

main "$@"
