#!/bin/bash
# command library for cisco, do not use outside of wazuh_netmgr

lib_register_node(){
    local method=$1
    local ip=$2
    local username=$3
    local password=$4
    local retcode=0
    local commands="
    enable
    conf t
    logging host $WAZUH_SERVER_IP
    logging trap informational
    end
    write memory
    exit"
    
    echo "Registering Cisco-vIOS with ip: $ip..."
    [ $VERBOSE -eq 1 ] && echo "Wazuh ip addr is $WAZUH_SERVER_IP"
    
    lib_execute_ssh "$method" "$ip" "$username" "$password" "$commands"
    
    retcode=$?
    [ $retcode -eq 0 ] && echo "Cisco-vIOS registration success" || echo "Cisco-vIOS registration failed"
    return $retcode
}

lib_unregister_node(){
    local method=$1
    local ip=$2
    local username=$3
    local password=$4
    local retcode=0
    local commands="
    enable
    conf t
    no logging host $WAZUH_SERVER_IP
    logging trap informational
    end
    write memory
    exit"
    
    echo "Unregistering Cisco-vIOS with ip: $ip..."
    [ $VERBOSE -eq 1 ] && echo "Wazuh ip addr is $WAZUH_SERVER_IP"
    
    lib_execute_ssh "$method" "$ip" "$username" "$password" "$commands"
    
    retcode=$?
    [ $retcode -eq 0 ] && echo "Cisco-vIOS unregistration success" || echo "Cisco-vIOS unregistration failed"
    return $retcode
}

